### PR TITLE
Fix full fetch logic (resolves #955)

### LINKED ISSUE #955: Project List has a limit of 50
Our Jira instance has hundreds of projects and I am part of a group that has access to all of them.

When I try to use `/jira subscribe` only the first 50 projects are in the list, alphabetically. I am not able to scroll down to see the rest.

**Steps to Reproduce:** 
1. `/Jira connect` in MM channel
2. `/Jira subscribe` in MM channel
3. Select "Project" dropdown
4. Scroll all the way to the end

**Expected Result:** I can see all of the projects I have access to.
**Actual Result:** The project list ends at 50 projects.

**Impact:** Currently the only workaround to this is to create more Jira user groups with specific project access. Most likely won't be using this feature until this is resolved.

Please let me know if there is a better workaround available.

### PR DESCRIPTION
**Pull request by relwell**
#### Summary
Pagination is broken for flows such as the `jira subscribe edit` workflow. Only 50 projects are currently listed, with no way to retrieve additional projects.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/955

### CODE REVIEW

**Comment by relwell** [comment]
@mickmister this has been an open issue for some time and is blocking some critical workflows for my team. Happy to work with you on this whenever you find the time. I just signed the CLA.

File: server/client_cloud.go [hunk 1]
```diff
@@ -107,11 +107,12 @@ func (client jiraCloudClient) ListProjects(query string, limit int, expandIssueT
...
-		if !fetchAll && remaining == 0 {
-			// Got enough.
-			return out, nil
+		if !fetchAll {
+			remaining -= len(result.Values)
+			if remaining == 0 {
+				// Got enough.
+				return out, nil
+			}
 		}
```
Comment (mickmister) [inline server/client_cloud.go:116]: It took me a while to understand the function in general here, as I initially missed the re-assignment of `remaining` on line 84. It seems the bug we're experiencing only occurs when `fetchAll` is `true`. Is this correct?

At the code's current state, I'm thinking we should always pass in `50` to line 94. Otherwise, we will always fetch all that we want in one request, except for when we want all of the results. Also, a variable called `remaining` doesn't really make sense in the case of `fetchAll` being `true`, which makes this harder to read because of that as well. Idk if we really need to change anything there though.

Also, I'm not sure if line 106 will ever be `true`, since we always fetch a max of `remaining` at a given time. 

Since it seems your change fixes the underlying issue you're experiencing, I'm approving this, though wondering your opinion on changing line 94 to always provide `50` for `maxResults`.

@raghavaggarwal2308 @avas27JTG What are your thoughts on the above?

---

As an aside, just to make sure there is no bug in the implementation for Jira Server, I took a look at the `ListProjects` function there. There is no loop there, and we just ask the Jira server for whatever it will return, as `&jira.GetQueryOptions` does not allow for any `maxResults` or `limit` parameter, and then adjust the output based on the `limit` provided to our function. Another comment on this, we generally want to be more conscious of performance issues on Jira Server rather than Jira Cloud, since that more directly impacts the performance of the customer's infrastructure in general.

https://github.com/mattermost/mattermost-plugin-jira/blob/e1430fa88131f700ff91624fec61f325a912d419/server/client_server.go#L179-L197

**Review by mickmister — APPROVED** [review]
Thanks for reporting and finding the root cause of this issue and fixing it @relwell 🚀 

The code in this `ListProjects` function is a bit confusing. Since it seems your change fixes the underlying issue you're experiencing, I'm approving this, though wondering your opinion on changing line 94 to always provide `50` for `maxResults`. If you think that change could cause a regression, I'm fine with keeping it as-is.

Also it seems the ticket linked in the PR description is unrelated to the PR. @relwell Do you mind creating an issue for the bug you are experiencing?

**Comment by relwell** [comment]
@mickmister sorry about the issue gaffe -- I've updated it to the proper repo, which should point to the correct issue.

This has been a longstanding problem that we're just trying to get solved to unblock some teams from using better chatops. So for that reason, I've just copied over the suggestion solution from within the chat. My other thought was indeed to simply set the limit to something arbitrarily higher (500 instead of 50, for instance). But if it truly is just a logic problem with pagination, this seems like the better solution.

I'm happy to make any change you'd prefer to see so long as we can get some more projects listed!

**Comment by mickmister** [comment]
Thanks @relwell 👍  I was unaware of that open issue https://github.com/mattermost/mattermost-plugin-jira/issues/955 until now. Thank you very much for solving this 🎉

File: server/client_cloud.go (hunk 1 above)
Comment (raghavaggarwal2308) [reply server/client_cloud.go:116]: > Since it seems your change fixes the underlying issue you're experiencing, I'm approving this, though wondering your opinion on changing line 94 to always provide 50 for maxResults.

@mickmister I agree with your suggestion. I think we can send `50` in all the cases except when the value of `limit` is "<50".

> Also, I'm not sure if line 106 will ever be true, since we always fetch a max of remaining at a given time.

I also think this condition is unnecessary.

Comment (relwell) [reply server/client_cloud.go:116]: Hi @raghavaggarwal2308, this solution was carried over from another user. While it's likely we can subtly improve the code, my team has been waiting a long time for a fix for this, so I would prefer we move forward at this point and defer any improvements to an additional iteration.

Comment (raghavaggarwal2308) [reply server/client_cloud.go:116]: @relwell Works for me 👍🏽.

**Comment by relwell** [comment]
@AayushChaudhary0001 @mickmister what are the next steps to getting this change merged?

**Comment by mickmister** [comment]
@relwell The change seems simple enough to me. We'll cover this in release testing cc @AayushChaudhary0001
