### PR TITLE
[GH-1087] Add "updated_priority" event param for legacy webhooks

### LINKED ISSUE #1087: UPDATED: updated_priority=1 option does not work
**UPDATE**: Code and Documentation has a typo! The command is **update_prioity**  and should be **update_priority**

This needs to be updated 

https://github.com/mattermost/mattermost-plugin-jira/blob/8ff19475757a65263766d3046922a2411aad4117/server/webhook_http.go#L31

image

I am on the latest version of the plugin 4.1.1 and mattermost is 9.5.4. I notice that **updated_priority=1**  does not seem to trigger the plugin updates. I am following these instructions --> https://docs.mattermost.com/integrate/jira-interoperability.html

My trigger is is PROJECT=XXX and issue CREATED/UPDATED. 

https://XXXXXXXX.com/plugins/jira/webhook?channel=test&secret=YYYYYYYY&team=technology&updated_priority=1

This does not trigger an update in mattermost when I change priority. I confirmed an update is sent by jira and the json payload is
 

>    "changelog": {
>         "id": "1294695",
>         "items": [
>             {
>                 "field": "priority",
>                 "fieldtype": "jira",
>                 "from": "2",
>                 "fromString": "Critical",
>                 "to": "3",
>                 "toString": "Major"
>             }
>         ]
>     }

 I did a test with various settings (labels, description, summary, priority...). 

Ex: 
 https://XXXXXXXX.com/plugins/jira/webhook?channel=test&secret=XXXXXX&team=technology&updated_labels=1&updated_description=1&updated_summary=1&updated_priority=1

All of them work except priority.

I have a workaround hack where I use **updated_all=1** . It captures priority changes but I would prefer to only be updated on priority updates. Any ideas what I can do? 

Thanks!

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- The "updated_priority" event param for legacy webhooks was misspelled as "updated_prioity". We added the correct event param without changing the existing one, so that the functionality of existing users does not get affected.
Documentation update PR: https://github.com/mattermost/docs/pull/7238

#### What to test:
- Users are getting notified for priority change event in for both event params i.e. "updated_priority" and "updated_prioity"

#### How to test:
- Install a Jira instance on you MM
- Do not connect your account
- Setup a [legacy webhook](https://docs.mattermost.com/integrate/jira-interoperability.html#legacy-jira-webhooks)
- Update the priority of any ticket on Jira

#### Ticket Link
Fixes #1087

### CODE REVIEW

**Comment by mickmister** [comment]
https://github.com/mattermost/docs/pull/7238 probably should have been left open until we release this change, but it's probably not a big deal in this case. Just something to keep in mind. You can use the `Do Not Merge` PR label in this case

File: server/webhook_http.go [hunk 1]
```diff
@@ -29,6 +29,7 @@ var eventParamMasks = map[string]StringSet{
 	"updated_description": NewStringSet(eventUpdatedDescription), // issue description edited
 	"updated_labels":      NewStringSet(eventUpdatedLabels),      // updated labels
 	"updated_prioity":     NewStringSet(eventUpdatedPriority),    // changes in priority
+	"updated_priority":    NewStringSet(eventUpdatedPriority),    // changes in priority
```
Comment (mickmister) [inline server/webhook_http.go:32]: Probably want to include a comment on the line above, saying we're keeping it around for backwards compatibility

Comment (raghavaggarwal2308) [reply server/webhook_http.go:32]: @mickmister Added the comment

**Review by mickmister — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]
