### PR TITLE
[GH-1014,1015] Added check for undefined fields and removed use of redux in tooltip component

### LINKED ISSUE #1014: Jira link tooltip error: Issue with Jira ticket having an empty `versions` field
This sanitized version of data that produced the issue can be used for testing. In the code below, it is the value of the `data` variable, so it can be hardcoded to the contents of this data file for testing.
[jira-plugin-test-data.json](https://github.com/mattermost/mattermost-plugin-jira/files/13866109/jira-plugin-test-data.json)

Reproduced on the community server, `data.fields.versions` is `undefined` on line 393 below:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'length')
    at zr (jira_issue_metadata.tsx:393:40)
```

https://github.com/mattermost/mattermost-plugin-jira/blob/249614ed5e5e061ca8301427c9421567d4117c9e/webapp/src/utils/jira_issue_metadata.tsx#L385-L396

---

Also I noticed when this happens, the error shows several times. It seems to happen for every many posts are visible at that time. Created a separate issue for this:  https://github.com/mattermost/mattermost-plugin-jira/issues/1015

### LINKED ISSUE #1015: Jira link tooltip error: When a render error happens for the link tooltip, this error occurs for all Jira ticket links currently visible in the center channel
This sanitized version of data that produced the issue can be used for testing. In the code below, it is the value of the `data` variable, so it can be hardcoded to the contents of this data file for testing.
[jira-plugin-test-data.json](https://github.com/mattermost/mattermost-plugin-jira/files/13866109/jira-plugin-test-data.json)

Also we should probably change the function signature below to `jiraIssueToReducer(data: TicketData | undefined)` as this is the case on first render of the page, before hovering on a Jira link. We should avoid calling this function before hovering over the particular link. This may be a change to be properly made in the core webapp, but we should handle it in the plugin first.

https://github.com/mattermost/mattermost-plugin-jira/blob/249614ed5e5e061ca8301427c9421567d4117c9e/webapp/src/utils/jira_issue_metadata.tsx#L378-L385

Also I noticed when this error happens, the error shows several times. It seems to happen for every post that is visible  at that time that contains a Jira ticket link. The error also shows on other tooltips (like GitHub links) after the first error happens.

I believe this means we may be attempting to fetch (if no error were to occur) all of the issues at once, upon the first hover of a Jira ticket link. Navigating to a different channel that contains posts with Jira ticket links causes those to all have errors as well. Note that at the moment, only one request is made upon hover on a Jira ticket link. No other request is made, even when hovering on other links or navigating to another channel.

Related issue: https://github.com/mattermost/mattermost-plugin-jira/issues/1014

---

As a side note, the webapp makes it so when this error happens, it catches the error using an [ErrorBoundary](https://legacy.reactjs.org/docs/error-boundaries.html), to avoid having the error bubble up and crash the webapp.

CleanShot 2024-01-08 at 15 35 58

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Added check for undefined fields in ticket data.
- Removed the use of redux in the tooltip component and used local state

#### What to test?
The tooltip is rendered properly on hovering on a Jira ticket link in a channel.

###### Steps to reproduce:
1. Connect your Jira account.
2. Hover over any Jira ticket link in a channel.

#### Ticket Link
Fixes #1014 
Fixes #1015

### CODE REVIEW

File: webapp/src/utils/jira_issue_metadata.tsx [hunk 1]
```diff
@@ -376,23 +376,25 @@ export function generateJQLStringFromSubscriptionFilters(issueMetadata: IssueMet
...
+        summary: data.fields && data.fields.summary,
         ticketId: data.key,
-        jiraIcon: data.fields.project.avatarUrls && data.fields.project.avatarUrls['48x48'],
-        versions: data.fields.versions.length ? data.fields.versions[0] : '',
-        statusKey: data.fields.status.name,
-        issueIcon: data.fields.issuetype.iconUrl,
+        jiraIcon: data.fields && data.fields.project && data.fields.project.avatarUrls && data.fields.project.avatarUrls['48x48'],
+        versions: data.fields && data.fields.versions && data.fields.versions.length ? data.fields.versions[0] : '',
+        statusKey: data.fields && data.fields.status && data.fields.status.name,
+        issueIcon: data.fields && data.fields.issuetype && data.fields.issuetype.iconUrl,
```
Comment (mickmister) [inline webapp/src/utils/jira_issue_metadata.tsx:397]: Since values in `TicketDataFields` can be `undefined` (e.g. the `versions` field), I think we should update the `TicketDataFields` type to reflect that, and then typescript will enforce that we return all defined things here.

**Review by mickmister — APPROVED** [review]
LGTM, just one suggestion for type safety

File: webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx [hunk 2]
```diff
@@ -243,7 +220,7 @@ export default class TicketPopover extends React.PureComponent<Props, State> {
                             target='_blank'
                             rel='noopener noreferrer'
                         >
-                            <h5>{ticketDetails.summary.substring(0, jiraTicketSummaryMaxLength)}</h5>
+                            <h5>{ticketDetails.summary && ticketDetails.summary.substring(0, jiraTicketSummaryMaxLength)}</h5>
```
Comment (mickmister) [inline webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx:223]: Then we can remove checks like this because we know it's a string

File: webapp/src/utils/jira_issue_metadata.tsx (hunk 1 above)
Comment (mickmister) [reply webapp/src/utils/jira_issue_metadata.tsx:397]: Values like `jiraIcon` may throw an error when giving an `img` element an undefined `src` prop, so we want to make sure these are all strings. Also, we probably want to have fallback images in case those are not defined.

**Comment by mickmister** [comment]
Merging for now so we can get more testing on this with the RC. Note that I think https://github.com/mattermost/mattermost-plugin-jira/issues/1018 should be addressed before we release this
