### PR TITLE
[MM-933] Updated code to display proper errors on UI

### LINKED ISSUE #933: SyntaxError: Unexpected end of JSON input
When create a issue from Mattermost  using /jira command
e.g.
/jira issue create this is a test
Can't search or select Assignee/Label/Assigner/Owner/....
It shows  "SyntaxError: Unexpected end of JSON input"

image

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Updated the backend code to return proper errors instead of empty responses for the "get-search-autocomplete-fields" and "get-search-users" API.
- Updated UI code to display a generic error in case of "get-search-autocomplete-fields" and "get-search-users" API calls.

#### Screenshot
error_fetching_Data

#### Ticket Link
Fixes #933

### CODE REVIEW

File: webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx [hunk 1]
```diff
@@ -44,6 +44,8 @@ export default class JiraAutoCompleteSelector extends React.PureComponent<Props>
                 value: suggestion.value,
                 label: stripHTML(suggestion.displayName),
             }));
+        }).catch((e) => {
+            throw new Error('Error fetching data');
```
Comment (Kshitij-Katiyar) [inline webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: constant for this ?

**Review by Kshitij-Katiyar — APPROVED** [review]

File: webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx (hunk 1 above)
Comment (raghavaggarwal2308) [reply webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: I don't think there is a need for this.

Comment (mickmister) [inline webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: We are sort of "swallowing" this error here. Is the error present in `e` helpful to the user at all?

Comment (mickmister) [reply webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: I guess I'm wondering why we're returning an error from the API if we're not using it on the frontend though

Comment (raghavaggarwal2308) [reply webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: @mickmister We want to show the error to the user in case we are unable to fetch the data. If we don't send the error from the API we won't be able to display the generic error. Please correct me if I am wrong

Comment (mickmister) [reply webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx:48]: Alright that makes sense

**Review by mickmister — APPROVED** [review]

File: server/autocomplete_search.go [hunk 2]
```diff
@@ -57,30 +55,28 @@ func (p *Plugin) httpGetSearchUsers(w http.ResponseWriter, r *http.Request) (int
...
-			errors.WithMessage(err, "failed to marshal response")
+		return respondErr(w, http.StatusInternalServerError, errors.WithMessage(err, "failed to marshal response"))
 	}
 
 	w.Header().Set("Content-Type", "application/json")
 	_, err = w.Write(bb)
 	if err != nil {
-		return http.StatusInternalServerError,
-			errors.WithMessage(err, "failed to write response")
+		return http.StatusInternalServerError, errors.WithMessage(err, "failed to write response")
```
Comment (mickmister) [inline server/autocomplete_search.go:79]: I notice we're not calling `respondErr` here. I think that's intentional since this error is coming from a failure to write a response

Comment (raghavaggarwal2308) [reply server/autocomplete_search.go:79]: @mickmister We were not calling `respondErr` anywhere in the function. I think we should as the user will not see any data in the dropdown in this case as well. Please let me know your thoughts on this.
