### PR TITLE
[GH-708] Fix check for autolink plug-in errors

### LINKED ISSUE #708: Check for autolink plugin panics
The check for the autolink plugin's availability logs an error, but it's referencing the wrong error variable. We also don't make sure the error is not nil before calling `.Error()`
https://github.com/mattermost/mattermost-plugin-jira/blob/789d142a062d5d82c87f3ff846d80360ea97c1ca/server/plugin.go#L310-L314

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/dwfqssit37fgfjqcad8n9stzyc) *by @mickmister*._

### PR DESCRIPTION
**Pull request by promulo**
#### Summary
This PR fixes a bug I stumbled upon when I was trying to reproduce #676 against the current `master`. That bug was causing the plug-in to crash due to the wrong error object being called during the warning log of autolink plug-in checks. Here I'm only making sure that the correct error object is used and only if it is not `nil`. More details can be found on the issue itself.

Thanks @mickmister for helping me with the troubleshooting.

#### Ticket Link
Fixes #708

### CODE REVIEW

File: server/plugin.go [hunk 1]
```diff
@@ -308,8 +308,12 @@ func (p *Plugin) OnActivate() error {
...
 
 			status, apiErr := p.API.GetPluginStatus(autolinkPluginId)
-			if apiErr != nil || status.State != model.PluginStateRunning {
-				p.API.LogWarn("OnActivate: Autolink plugin is unavailable", "error", err.Error(), "status", status)
+			if apiErr != nil {
+				p.API.LogWarn("OnActivate: Autolink plugin unavailable. API returned error", "error", apiErr.Error())
+				continue
+			}
+			if status.State != model.PluginStateRunning {
+				p.API.LogWarn("OnActivate: Autolink plugin unavailable. Plug-in is not running", "status", status)
```
Comment (mickmister) [inline server/plugin.go:316]: We hardly ever refer to `plugin` as `plug-in`, so I suggest removing the `-` in this message

```suggestion
				p.API.LogWarn("OnActivate: Autolink plugin unavailable. Plugin is not running", "status", status)
```

**Review by mickmister — APPROVED** [review]
Awesome job @promulo! The fix looks great, I just have one non-blocking suggestion on log message wording

File: server/plugin.go (hunk 1 above)
Comment (promulo) [reply server/plugin.go]: Sounds sensible. Just changed.

**Review by hanzei — APPROVED** [review]
LGTM.

Let's merge this quickly.
