### PR TITLE
Fixed handling expired credentials

### LINKED ISSUE #588: Cant connect user via /jira connect
Environment:
- Self-hosted JIRA 8.5.1
- Self-hosted Mattermost 5.23.1
   - Jira Plugin 2.4.0

I get an error when connecting a user to Jira after entering the JIRA credentials:

**failed to get temporary credentials for moa9qizt1in3zf9gcz4c54rp3e: unexpected end of JSON input**

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<style>
			body {
				color: rgb(23, 43, 77);
				letter-spacing: -0.01em;
			}

			.flex-parent {
				padding: 50px;
			}

			.message-container {
				padding: 1.6em 0 0.8em;
				opacity: .6;
			}
		</style>
		<link rel="stylesheet" href="https://unpkg.com/@atlaskit/css-reset@2.0.0/dist/bundle.css" media="all">
	</head>
	<body>
		<div class="flex-parent">
			<h3>
				Failed to connect to Jira.
			</h3>
			<div class="message-container">
				<div>Failed to get temporary credentials for moa9qizt1in3zf9gcz4c54rp3e: unexpected end of JSON input</div>
			</div>
		</div>
	</body>
</html>
```

I assume it has to do with user access rights, but I cant find any documentation how to fix this problem ...

### PR DESCRIPTION
**Pull request by levb**
Fixes #588 

My best guess is that the credentials expired (after 15 minutes), improved the error message

### CODE REVIEW

File: server/kv.go [hunk 1]
```diff
@@ -644,6 +644,11 @@ func (store store) OneTimeLoadOauth1aTemporaryCredentials(mmUserId string) (*OAu
 	if appErr != nil {
 		return nil, errors.WithMessage(appErr, "failed to load temporary credentials for "+mmUserId)
 	}
+	// If the key expired, appErr is nil, but the data is also nil
+	if len(b) == 0 {
```
Comment (hanzei) [inline server/kv.go:648]: Nit pick: The check should be if the data was not found, not if it's an empty slice.
```suggestion
	if b == nil {
```

**Comment by levb** [comment]
@DHaussermann please approve this one, it should be CP-ed into v3

**Comment by DHaussermann** [comment]
@lev I can't find repo steps for this. Tested time out before authenticating (as in the linked issue) as well as before clicking `allow`. 

I end up here `http://dkh-jira.ngrok.io/plugins/servlet/oauth/authorize` but, it seems it's just a page provided by the Jira app that handles this. 

Expired


After the code change I still see the same behavior and not the new error message you have added. Any thoughts on how to specifically hit the change you've made?

**Comment by DHaussermann** [comment]
@levb  I can't find repo steps for this. Tested time out before authenticating (as in the linked issue) as well as before clicking `allow`. 

I end up here `http://dkh-jira.ngrok.io/plugins/servlet/oauth/authorize` but, it seems it's just a page provided by the Jira app that handles this. 

Expired


After the code change I still see the same behavior and not the new error message you have added. Any thoughts on how to specifically hit the change you've made?

**Comment by levb** [comment]
CP-ed into EE
