### PR TITLE
[MM-49] Fix invalid Jira links in posts

### LINKED ISSUE #1012: Invalid Jira links in posts
#### Summary
The links for the Jira webhook page and Jira application links page are invalid.

#### Screenshots:
image

image

#### Steps to reproduce:
- Run the `/jira webhook` command.
- Uninstall an installed cloud oauth instance.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
Fixed the links for the Jira webhook page and Jira application links page.

#### Ticket Link
Fixes #1012

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

File: server/instance_cloud_oauth.go [hunk 1]
```diff
@@ -218,11 +218,11 @@ func (ci *cloudOAuthInstance) GetJiraBaseURL() string {
 }
 
 func (ci *cloudOAuthInstance) GetManageAppsURL() string {
-	return fmt.Sprintf("%s/plugins/servlet/applinks/listApplicationLinks", ci.GetURL())
+	return fmt.Sprintf("%s/plugins/servlet/applinks/listApplicationLinks", ci.GetJiraBaseURL())
```
Comment (mickmister) [inline server/instance_cloud_oauth.go:221]: @raghavaggarwal2308 Are there any other similar changes that may need to be made throughout the plugin?

Comment (raghavaggarwal2308) [reply server/instance_cloud_oauth.go:221]: @mickmister Nothing I observed as of now.
